// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CompSciProblemType string

const (
	CompSciProblemTypeExam     CompSciProblemType = "exam"
	CompSciProblemTypePractice CompSciProblemType = "practice"
)

func (e *CompSciProblemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompSciProblemType(s)
	case string:
		*e = CompSciProblemType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompSciProblemType: %T", src)
	}
	return nil
}

type NullCompSciProblemType struct {
	CompSciProblemType CompSciProblemType `json:"comp_sci_problem_type"`
	Valid              bool               `json:"valid"` // Valid is true if CompSciProblemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompSciProblemType) Scan(value interface{}) error {
	if value == nil {
		ns.CompSciProblemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompSciProblemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompSciProblemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompSciProblemType), nil
}

type UserRole string

const (
	UserRoleStudent UserRole = "student"
	UserRoleTeacher UserRole = "teacher"
	UserRoleAdmin   UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type CompSciProblem struct {
	ID            int64            `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	GroupID       int64            `json:"group_id"`
	Name          string           `json:"name"`
	Description   string           `json:"description"`
	ProblemText   string           `json:"problem_text"`
	TimeLimitMs   pgtype.Int4      `json:"time_limit_ms"`
	MemoryLimitMb pgtype.Int4      `json:"memory_limit_mb"`
}

type CompSciProblemGroup struct {
	ID          int64              `json:"id"`
	CreatedAt   pgtype.Timestamp   `json:"created_at"`
	UpdatedAt   pgtype.Timestamp   `json:"updated_at"`
	Type        CompSciProblemType `json:"type"`
	CourseID    int64              `json:"course_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
}

type CompSciSubmission struct {
	ID          int64            `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UserID      int64            `json:"user_id"`
	ProblemID   int64            `json:"problem_id"`
	Code        string           `json:"code"`
	Score       int32            `json:"score"`
	MaxScore    int32            `json:"max_score"`
	PassedTests int32            `json:"passed_tests"`
	TotalTests  int32            `json:"total_tests"`
	ResultsJson string           `json:"results_json"`
}

type CompSciTestCase struct {
	ID            int64            `json:"id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	ProblemID     int64            `json:"problem_id"`
	Input         string           `json:"input"`
	Output        string           `json:"output"`
	CorrectPoints int32            `json:"correct_points"`
}

type Course struct {
	ID          int64            `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Name        string           `json:"name"`
	Institution string           `json:"institution"`
}

type User struct {
	ID          int64            `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Email       string           `json:"email"`
	Institution string           `json:"institution"`
	FullName    string           `json:"full_name"`
	GivenName   string           `json:"given_name"`
	Role        UserRole         `json:"role"`
}

type UserCourse struct {
	ID        int64            `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	UserID    int64            `json:"user_id"`
	CourseID  int64            `json:"course_id"`
}
