// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCompSciProblem = `-- name: CreateCompSciProblem :one
INSERT INTO
    comp_sci_problems (
        group_id,
        name,
        description,
        problem_text,
        time_limit_ms,
        memory_limit_mb
    )
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, created_at, updated_at, group_id, name, description, problem_text, time_limit_ms, memory_limit_mb
`

type CreateCompSciProblemParams struct {
	GroupID       int64       `json:"group_id"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	ProblemText   string      `json:"problem_text"`
	TimeLimitMs   pgtype.Int4 `json:"time_limit_ms"`
	MemoryLimitMb pgtype.Int4 `json:"memory_limit_mb"`
}

func (q *Queries) CreateCompSciProblem(ctx context.Context, arg CreateCompSciProblemParams) (CompSciProblem, error) {
	row := q.db.QueryRow(ctx, createCompSciProblem,
		arg.GroupID,
		arg.Name,
		arg.Description,
		arg.ProblemText,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
	)
	var i CompSciProblem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.ProblemText,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
	)
	return i, err
}

const createCompSciProblemGroup = `-- name: CreateCompSciProblemGroup :one
INSERT INTO
    comp_sci_problem_group (
        type,
        course_id,
        name,
        description
    )
VALUES ($1, $2, $3, $4) RETURNING id, created_at, updated_at, type, course_id, name, description
`

type CreateCompSciProblemGroupParams struct {
	Type        CompSciProblemType `json:"type"`
	CourseID    int64              `json:"course_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
}

func (q *Queries) CreateCompSciProblemGroup(ctx context.Context, arg CreateCompSciProblemGroupParams) (CompSciProblemGroup, error) {
	row := q.db.QueryRow(ctx, createCompSciProblemGroup,
		arg.Type,
		arg.CourseID,
		arg.Name,
		arg.Description,
	)
	var i CompSciProblemGroup
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.CourseID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const createCompSciSubmission = `-- name: CreateCompSciSubmission :one
INSERT INTO
    comp_sci_submissions (
        user_id,
        problem_id,
        code,
        score,
        max_score,
        passed_tests,
        total_tests,
        results_json
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    ) RETURNING id, created_at, user_id, problem_id, code, score, max_score, passed_tests, total_tests, results_json
`

type CreateCompSciSubmissionParams struct {
	UserID      int64  `json:"user_id"`
	ProblemID   int64  `json:"problem_id"`
	Code        string `json:"code"`
	Score       int32  `json:"score"`
	MaxScore    int32  `json:"max_score"`
	PassedTests int32  `json:"passed_tests"`
	TotalTests  int32  `json:"total_tests"`
	ResultsJson string `json:"results_json"`
}

func (q *Queries) CreateCompSciSubmission(ctx context.Context, arg CreateCompSciSubmissionParams) (CompSciSubmission, error) {
	row := q.db.QueryRow(ctx, createCompSciSubmission,
		arg.UserID,
		arg.ProblemID,
		arg.Code,
		arg.Score,
		arg.MaxScore,
		arg.PassedTests,
		arg.TotalTests,
		arg.ResultsJson,
	)
	var i CompSciSubmission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.ProblemID,
		&i.Code,
		&i.Score,
		&i.MaxScore,
		&i.PassedTests,
		&i.TotalTests,
		&i.ResultsJson,
	)
	return i, err
}

const createCompSciTestCase = `-- name: CreateCompSciTestCase :one
INSERT INTO
    comp_sci_test_cases (
        problem_id,
        input,
        output,
        correct_points
    )
VALUES ($1, $2, $3, $4) RETURNING id, created_at, updated_at, problem_id, input, output, correct_points
`

type CreateCompSciTestCaseParams struct {
	ProblemID     int64  `json:"problem_id"`
	Input         string `json:"input"`
	Output        string `json:"output"`
	CorrectPoints int32  `json:"correct_points"`
}

func (q *Queries) CreateCompSciTestCase(ctx context.Context, arg CreateCompSciTestCaseParams) (CompSciTestCase, error) {
	row := q.db.QueryRow(ctx, createCompSciTestCase,
		arg.ProblemID,
		arg.Input,
		arg.Output,
		arg.CorrectPoints,
	)
	var i CompSciTestCase
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProblemID,
		&i.Input,
		&i.Output,
		&i.CorrectPoints,
	)
	return i, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (name, institution) VALUES ($1, $2) RETURNING id, created_at, updated_at, name, institution
`

type CreateCourseParams struct {
	Name        string `json:"name"`
	Institution string `json:"institution"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse, arg.Name, arg.Institution)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Institution,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (
        email,
        institution,
        full_name,
        given_name,
        role
    )
VALUES ($1, $2, $3, $4, $5) RETURNING id, created_at, updated_at, email, institution, full_name, given_name, role
`

type CreateUserParams struct {
	Email       string   `json:"email"`
	Institution string   `json:"institution"`
	FullName    string   `json:"full_name"`
	GivenName   string   `json:"given_name"`
	Role        UserRole `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Institution,
		arg.FullName,
		arg.GivenName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Institution,
		&i.FullName,
		&i.GivenName,
		&i.Role,
	)
	return i, err
}

const createUserCourse = `-- name: CreateUserCourse :one
INSERT INTO
    user_courses (user_id, course_id)
VALUES ($1, $2) RETURNING id, created_at, updated_at, user_id, course_id
`

type CreateUserCourseParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) CreateUserCourse(ctx context.Context, arg CreateUserCourseParams) (UserCourse, error) {
	row := q.db.QueryRow(ctx, createUserCourse, arg.UserID, arg.CourseID)
	var i UserCourse
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.CourseID,
	)
	return i, err
}

const deleteCompSciProblem = `-- name: DeleteCompSciProblem :exec
DELETE FROM comp_sci_problems WHERE id = $1
`

func (q *Queries) DeleteCompSciProblem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCompSciProblem, id)
	return err
}

const deleteCompSciProblemGroup = `-- name: DeleteCompSciProblemGroup :exec
DELETE FROM comp_sci_problem_group WHERE id = $1
`

func (q *Queries) DeleteCompSciProblemGroup(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCompSciProblemGroup, id)
	return err
}

const deleteCompSciTestCase = `-- name: DeleteCompSciTestCase :exec
DELETE FROM comp_sci_test_cases WHERE id = $1
`

func (q *Queries) DeleteCompSciTestCase(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCompSciTestCase, id)
	return err
}

const deleteCourse = `-- name: DeleteCourse :exec
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCourse, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserCourse = `-- name: DeleteUserCourse :exec
DELETE FROM user_courses WHERE id = $1
`

func (q *Queries) DeleteUserCourse(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUserCourse, id)
	return err
}

const deleteUserCourseByUserAndCourse = `-- name: DeleteUserCourseByUserAndCourse :exec
DELETE FROM user_courses WHERE user_id = $1 AND course_id = $2
`

type DeleteUserCourseByUserAndCourseParams struct {
	UserID   int64 `json:"user_id"`
	CourseID int64 `json:"course_id"`
}

func (q *Queries) DeleteUserCourseByUserAndCourse(ctx context.Context, arg DeleteUserCourseByUserAndCourseParams) error {
	_, err := q.db.Exec(ctx, deleteUserCourseByUserAndCourse, arg.UserID, arg.CourseID)
	return err
}

const getCompSciProblem = `-- name: GetCompSciProblem :one

SELECT id, created_at, updated_at, group_id, name, description, problem_text, time_limit_ms, memory_limit_mb FROM comp_sci_problems WHERE id = $1 LIMIT 1
`

// =====================
// Computer Science Problems
// =====================
func (q *Queries) GetCompSciProblem(ctx context.Context, id int64) (CompSciProblem, error) {
	row := q.db.QueryRow(ctx, getCompSciProblem, id)
	var i CompSciProblem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.ProblemText,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
	)
	return i, err
}

const getCompSciProblemGroup = `-- name: GetCompSciProblemGroup :one

SELECT id, created_at, updated_at, type, course_id, name, description FROM comp_sci_problem_group WHERE id = $1 LIMIT 1
`

// =====================
// Computer Science Problem Groups
// =====================
func (q *Queries) GetCompSciProblemGroup(ctx context.Context, id int64) (CompSciProblemGroup, error) {
	row := q.db.QueryRow(ctx, getCompSciProblemGroup, id)
	var i CompSciProblemGroup
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.CourseID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getCompSciSubmission = `-- name: GetCompSciSubmission :one

SELECT id, created_at, user_id, problem_id, code, score, max_score, passed_tests, total_tests, results_json FROM comp_sci_submissions WHERE id = $1 LIMIT 1
`

// =====================
// Computer Science Submissions
// =====================
func (q *Queries) GetCompSciSubmission(ctx context.Context, id int64) (CompSciSubmission, error) {
	row := q.db.QueryRow(ctx, getCompSciSubmission, id)
	var i CompSciSubmission
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UserID,
		&i.ProblemID,
		&i.Code,
		&i.Score,
		&i.MaxScore,
		&i.PassedTests,
		&i.TotalTests,
		&i.ResultsJson,
	)
	return i, err
}

const getCompSciTestCase = `-- name: GetCompSciTestCase :one

SELECT id, created_at, updated_at, problem_id, input, output, correct_points FROM comp_sci_test_cases WHERE id = $1 LIMIT 1
`

// =====================
// Computer Science Test Cases
// =====================
func (q *Queries) GetCompSciTestCase(ctx context.Context, id int64) (CompSciTestCase, error) {
	row := q.db.QueryRow(ctx, getCompSciTestCase, id)
	var i CompSciTestCase
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProblemID,
		&i.Input,
		&i.Output,
		&i.CorrectPoints,
	)
	return i, err
}

const getCourse = `-- name: GetCourse :one

SELECT id, created_at, updated_at, name, institution FROM courses WHERE id = $1 LIMIT 1
`

// =====================
// Courses
// =====================
func (q *Queries) GetCourse(ctx context.Context, id int64) (Course, error) {
	row := q.db.QueryRow(ctx, getCourse, id)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Institution,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, created_at, updated_at, email, institution, full_name, given_name, role FROM users WHERE id = $1 LIMIT 1
`

// =====================
// Users
// =====================
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Institution,
		&i.FullName,
		&i.GivenName,
		&i.Role,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, institution, full_name, given_name, role FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Institution,
		&i.FullName,
		&i.GivenName,
		&i.Role,
	)
	return i, err
}

const getUserCourse = `-- name: GetUserCourse :one

SELECT id, created_at, updated_at, user_id, course_id FROM user_courses WHERE id = $1 LIMIT 1
`

// =====================
// User Courses (Enrollments)
// =====================
func (q *Queries) GetUserCourse(ctx context.Context, id int64) (UserCourse, error) {
	row := q.db.QueryRow(ctx, getUserCourse, id)
	var i UserCourse
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.CourseID,
	)
	return i, err
}

const listCompSciProblemGroups = `-- name: ListCompSciProblemGroups :many
SELECT id, created_at, updated_at, type, course_id, name, description FROM comp_sci_problem_group ORDER BY id
`

func (q *Queries) ListCompSciProblemGroups(ctx context.Context) ([]CompSciProblemGroup, error) {
	rows, err := q.db.Query(ctx, listCompSciProblemGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciProblemGroup
	for rows.Next() {
		var i CompSciProblemGroup
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.CourseID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSciProblemGroupsByCourse = `-- name: ListCompSciProblemGroupsByCourse :many
SELECT id, created_at, updated_at, type, course_id, name, description
FROM comp_sci_problem_group
WHERE
    course_id = $1
ORDER BY id
`

func (q *Queries) ListCompSciProblemGroupsByCourse(ctx context.Context, courseID int64) ([]CompSciProblemGroup, error) {
	rows, err := q.db.Query(ctx, listCompSciProblemGroupsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciProblemGroup
	for rows.Next() {
		var i CompSciProblemGroup
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.CourseID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSciProblemGroupsByType = `-- name: ListCompSciProblemGroupsByType :many
SELECT id, created_at, updated_at, type, course_id, name, description FROM comp_sci_problem_group WHERE type = $1 ORDER BY id
`

func (q *Queries) ListCompSciProblemGroupsByType(ctx context.Context, type_ CompSciProblemType) ([]CompSciProblemGroup, error) {
	rows, err := q.db.Query(ctx, listCompSciProblemGroupsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciProblemGroup
	for rows.Next() {
		var i CompSciProblemGroup
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Type,
			&i.CourseID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSciProblems = `-- name: ListCompSciProblems :many
SELECT id, created_at, updated_at, group_id, name, description, problem_text, time_limit_ms, memory_limit_mb FROM comp_sci_problems ORDER BY id
`

func (q *Queries) ListCompSciProblems(ctx context.Context) ([]CompSciProblem, error) {
	rows, err := q.db.Query(ctx, listCompSciProblems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciProblem
	for rows.Next() {
		var i CompSciProblem
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.ProblemText,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSciProblemsByGroup = `-- name: ListCompSciProblemsByGroup :many
SELECT id, created_at, updated_at, group_id, name, description, problem_text, time_limit_ms, memory_limit_mb FROM comp_sci_problems WHERE group_id = $1 ORDER BY id
`

func (q *Queries) ListCompSciProblemsByGroup(ctx context.Context, groupID int64) ([]CompSciProblem, error) {
	rows, err := q.db.Query(ctx, listCompSciProblemsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciProblem
	for rows.Next() {
		var i CompSciProblem
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GroupID,
			&i.Name,
			&i.Description,
			&i.ProblemText,
			&i.TimeLimitMs,
			&i.MemoryLimitMb,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSciSubmissionsByProblem = `-- name: ListCompSciSubmissionsByProblem :many
SELECT id, created_at, user_id, problem_id, code, score, max_score, passed_tests, total_tests, results_json
FROM comp_sci_submissions
WHERE
    problem_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCompSciSubmissionsByProblem(ctx context.Context, problemID int64) ([]CompSciSubmission, error) {
	rows, err := q.db.Query(ctx, listCompSciSubmissionsByProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciSubmission
	for rows.Next() {
		var i CompSciSubmission
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.ProblemID,
			&i.Code,
			&i.Score,
			&i.MaxScore,
			&i.PassedTests,
			&i.TotalTests,
			&i.ResultsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSciSubmissionsByUser = `-- name: ListCompSciSubmissionsByUser :many
SELECT id, created_at, user_id, problem_id, code, score, max_score, passed_tests, total_tests, results_json
FROM comp_sci_submissions
WHERE
    user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCompSciSubmissionsByUser(ctx context.Context, userID int64) ([]CompSciSubmission, error) {
	rows, err := q.db.Query(ctx, listCompSciSubmissionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciSubmission
	for rows.Next() {
		var i CompSciSubmission
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.ProblemID,
			&i.Code,
			&i.Score,
			&i.MaxScore,
			&i.PassedTests,
			&i.TotalTests,
			&i.ResultsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSciSubmissionsByUserAndProblem = `-- name: ListCompSciSubmissionsByUserAndProblem :many
SELECT id, created_at, user_id, problem_id, code, score, max_score, passed_tests, total_tests, results_json
FROM comp_sci_submissions
WHERE
    user_id = $1
    AND problem_id = $2
ORDER BY created_at DESC
`

type ListCompSciSubmissionsByUserAndProblemParams struct {
	UserID    int64 `json:"user_id"`
	ProblemID int64 `json:"problem_id"`
}

func (q *Queries) ListCompSciSubmissionsByUserAndProblem(ctx context.Context, arg ListCompSciSubmissionsByUserAndProblemParams) ([]CompSciSubmission, error) {
	rows, err := q.db.Query(ctx, listCompSciSubmissionsByUserAndProblem, arg.UserID, arg.ProblemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciSubmission
	for rows.Next() {
		var i CompSciSubmission
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.ProblemID,
			&i.Code,
			&i.Score,
			&i.MaxScore,
			&i.PassedTests,
			&i.TotalTests,
			&i.ResultsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSciTestCases = `-- name: ListCompSciTestCases :many
SELECT id, created_at, updated_at, problem_id, input, output, correct_points FROM comp_sci_test_cases ORDER BY id
`

func (q *Queries) ListCompSciTestCases(ctx context.Context) ([]CompSciTestCase, error) {
	rows, err := q.db.Query(ctx, listCompSciTestCases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciTestCase
	for rows.Next() {
		var i CompSciTestCase
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProblemID,
			&i.Input,
			&i.Output,
			&i.CorrectPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompSciTestCasesByProblem = `-- name: ListCompSciTestCasesByProblem :many
SELECT id, created_at, updated_at, problem_id, input, output, correct_points FROM comp_sci_test_cases WHERE problem_id = $1 ORDER BY id
`

func (q *Queries) ListCompSciTestCasesByProblem(ctx context.Context, problemID int64) ([]CompSciTestCase, error) {
	rows, err := q.db.Query(ctx, listCompSciTestCasesByProblem, problemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompSciTestCase
	for rows.Next() {
		var i CompSciTestCase
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProblemID,
			&i.Input,
			&i.Output,
			&i.CorrectPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCourses = `-- name: ListCourses :many
SELECT id, created_at, updated_at, name, institution FROM courses ORDER BY id
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Institution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByInstitution = `-- name: ListCoursesByInstitution :many
SELECT id, created_at, updated_at, name, institution FROM courses WHERE institution = $1 ORDER BY id
`

func (q *Queries) ListCoursesByInstitution(ctx context.Context, institution string) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesByInstitution, institution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Institution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesByUser = `-- name: ListCoursesByUser :many
SELECT c.id, c.created_at, c.updated_at, c.name, c.institution
FROM courses c
    JOIN user_courses uc ON c.id = uc.course_id
WHERE
    uc.user_id = $1
ORDER BY c.id
`

func (q *Queries) ListCoursesByUser(ctx context.Context, userID int64) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Institution,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCoursesByCourse = `-- name: ListUserCoursesByCourse :many
SELECT id, created_at, updated_at, user_id, course_id FROM user_courses WHERE course_id = $1 ORDER BY id
`

func (q *Queries) ListUserCoursesByCourse(ctx context.Context, courseID int64) ([]UserCourse, error) {
	rows, err := q.db.Query(ctx, listUserCoursesByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCourse
	for rows.Next() {
		var i UserCourse
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.CourseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCoursesByUser = `-- name: ListUserCoursesByUser :many
SELECT id, created_at, updated_at, user_id, course_id FROM user_courses WHERE user_id = $1 ORDER BY id
`

func (q *Queries) ListUserCoursesByUser(ctx context.Context, userID int64) ([]UserCourse, error) {
	rows, err := q.db.Query(ctx, listUserCoursesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCourse
	for rows.Next() {
		var i UserCourse
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.CourseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, created_at, updated_at, email, institution, full_name, given_name, role FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Institution,
			&i.FullName,
			&i.GivenName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByInstitution = `-- name: ListUsersByInstitution :many
SELECT id, created_at, updated_at, email, institution, full_name, given_name, role FROM users WHERE institution = $1 ORDER BY id
`

func (q *Queries) ListUsersByInstitution(ctx context.Context, institution string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByInstitution, institution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.Institution,
			&i.FullName,
			&i.GivenName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompSciProblem = `-- name: UpdateCompSciProblem :one
UPDATE comp_sci_problems
SET
    group_id = $2,
    name = $3,
    description = $4,
    problem_text = $5,
    time_limit_ms = $6,
    memory_limit_mb = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1 RETURNING id, created_at, updated_at, group_id, name, description, problem_text, time_limit_ms, memory_limit_mb
`

type UpdateCompSciProblemParams struct {
	ID            int64       `json:"id"`
	GroupID       int64       `json:"group_id"`
	Name          string      `json:"name"`
	Description   string      `json:"description"`
	ProblemText   string      `json:"problem_text"`
	TimeLimitMs   pgtype.Int4 `json:"time_limit_ms"`
	MemoryLimitMb pgtype.Int4 `json:"memory_limit_mb"`
}

func (q *Queries) UpdateCompSciProblem(ctx context.Context, arg UpdateCompSciProblemParams) (CompSciProblem, error) {
	row := q.db.QueryRow(ctx, updateCompSciProblem,
		arg.ID,
		arg.GroupID,
		arg.Name,
		arg.Description,
		arg.ProblemText,
		arg.TimeLimitMs,
		arg.MemoryLimitMb,
	)
	var i CompSciProblem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GroupID,
		&i.Name,
		&i.Description,
		&i.ProblemText,
		&i.TimeLimitMs,
		&i.MemoryLimitMb,
	)
	return i, err
}

const updateCompSciProblemGroup = `-- name: UpdateCompSciProblemGroup :one
UPDATE comp_sci_problem_group
SET
    type = $2,
    course_id = $3,
    name = $4,
    description = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1 RETURNING id, created_at, updated_at, type, course_id, name, description
`

type UpdateCompSciProblemGroupParams struct {
	ID          int64              `json:"id"`
	Type        CompSciProblemType `json:"type"`
	CourseID    int64              `json:"course_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
}

func (q *Queries) UpdateCompSciProblemGroup(ctx context.Context, arg UpdateCompSciProblemGroupParams) (CompSciProblemGroup, error) {
	row := q.db.QueryRow(ctx, updateCompSciProblemGroup,
		arg.ID,
		arg.Type,
		arg.CourseID,
		arg.Name,
		arg.Description,
	)
	var i CompSciProblemGroup
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Type,
		&i.CourseID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const updateCompSciTestCase = `-- name: UpdateCompSciTestCase :one
UPDATE comp_sci_test_cases
SET
    problem_id = $2,
    input = $3,
    output = $4,
    correct_points = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1 RETURNING id, created_at, updated_at, problem_id, input, output, correct_points
`

type UpdateCompSciTestCaseParams struct {
	ID            int64  `json:"id"`
	ProblemID     int64  `json:"problem_id"`
	Input         string `json:"input"`
	Output        string `json:"output"`
	CorrectPoints int32  `json:"correct_points"`
}

func (q *Queries) UpdateCompSciTestCase(ctx context.Context, arg UpdateCompSciTestCaseParams) (CompSciTestCase, error) {
	row := q.db.QueryRow(ctx, updateCompSciTestCase,
		arg.ID,
		arg.ProblemID,
		arg.Input,
		arg.Output,
		arg.CorrectPoints,
	)
	var i CompSciTestCase
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProblemID,
		&i.Input,
		&i.Output,
		&i.CorrectPoints,
	)
	return i, err
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET
    name = $2,
    institution = $3,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1 RETURNING id, created_at, updated_at, name, institution
`

type UpdateCourseParams struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Institution string `json:"institution"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse, arg.ID, arg.Name, arg.Institution)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Institution,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email = $2,
    institution = $3,
    full_name = $4,
    given_name = $5,
    role = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = $1 RETURNING id, created_at, updated_at, email, institution, full_name, given_name, role
`

type UpdateUserParams struct {
	ID          int64    `json:"id"`
	Email       string   `json:"email"`
	Institution string   `json:"institution"`
	FullName    string   `json:"full_name"`
	GivenName   string   `json:"given_name"`
	Role        UserRole `json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Institution,
		arg.FullName,
		arg.GivenName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.Institution,
		&i.FullName,
		&i.GivenName,
		&i.Role,
	)
	return i, err
}
